# Generated by Django 5.2.1 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default='Ourinhos', verbose_name='Local'),
            preserve_default=False,
        ),
    ]
