# Generated by Django 5.2.1 on 2025-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
    ]
